#!/usr/bin/env node
/**
 * rename-site.mjs — rename a site slug across all source files
 *
 * Generated by the dashboard "Rename" button (or run directly).
 *
 * Usage:
 *   node _scripts/rename-site.mjs <old-slug> <new-slug>
 *
 * After running, commit with:
 *   git add -A && git commit -m "refactor: rename <old> → <new>"
 */

import { execSync }                              from 'child_process';
import { readFileSync, writeFileSync, existsSync } from 'fs';
import { join, resolve }                         from 'path';

const root = resolve('.');
const [oldSlug, newSlug] = process.argv.slice(2);

if (!oldSlug || !newSlug) {
  console.error(
    '\nUsage: node _scripts/rename-site.mjs <old-slug> <new-slug>\n' +
    '\nOr use the dashboard "Rename" button — it generates the command.\n'
  );
  process.exit(1);
}

const oldPath = join(root, 'sites', oldSlug);
const newPath = join(root, 'sites', newSlug);

const today = new Date().toISOString().slice(0, 10);

console.log(`\n${'─'.repeat(56)}`);
console.log(` Rename site — ${today}`);
console.log('─'.repeat(56));

// ── Preflight ─────────────────────────────────────────────────────────────────
if (!existsSync(oldPath)) {
  console.error(`  ✖  sites/${oldSlug} not found`);
  process.exit(1);
}
if (existsSync(newPath)) {
  console.error(`  ✖  sites/${newSlug} already exists — choose a different name`);
  process.exit(1);
}

// ── git mv ────────────────────────────────────────────────────────────────────
execSync(`git mv sites/${oldSlug} sites/${newSlug}`, { cwd: root, stdio: 'inherit' });
console.log(`  ✓  moved      sites/${oldSlug} → sites/${newSlug}`);

// ── wiring.json ───────────────────────────────────────────────────────────────
const wiringPath = join(newPath, 'wiring.json');
if (existsSync(wiringPath)) {
  let w;
  try   { w = JSON.parse(readFileSync(wiringPath, 'utf-8')); }
  catch { console.error(`  ✖  wiring.json: parse error — fix manually`); process.exit(1); }

  if (w.site === oldSlug)  w.site = newSlug;
  if (w.slug === oldSlug)  w.slug = newSlug;
  if (w.sandbox_url)
    w.sandbox_url = w.sandbox_url.replace(
      `WebsiteMocker/${oldSlug}`, `WebsiteMocker/${newSlug}`
    );

  writeFileSync(wiringPath, JSON.stringify(w, null, 2) + '\n');
  console.log(`  ✓  updated   wiring.json`);
}

// ── astro.config.mjs ──────────────────────────────────────────────────────────
const configPath = join(newPath, 'astro.config.mjs');
if (existsSync(configPath)) {
  const original = readFileSync(configPath, 'utf-8');
  const updated  = original.replaceAll(
    `/WebsiteMocker/${oldSlug}`,
    `/WebsiteMocker/${newSlug}`
  );
  if (updated !== original) {
    writeFileSync(configPath, updated);
    console.log(`  ✓  updated   astro.config.mjs`);
  }
}

// ── Summary ───────────────────────────────────────────────────────────────────
console.log(`\n${'─'.repeat(56)}`);
console.log(' Done. Commit with:\n');
console.log(`   git add -A && git commit -m "refactor: rename ${oldSlug} → ${newSlug}"`);
console.log('   git push\n');
console.log(' Then rebuild the sandbox:\n');
console.log('   npm run build\n');
